# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f32c3436f2f2fbc18a23230699b99710a99dc6f24300e550f2cd77949d7ff5d2c8ef34f7873eb1b640956846946dbd35d1c7abd5214a5f3e653c89b687c150f

test:
  secret_key_base: 92d2b26da4abbf3b0d9afa21efcfec71f3ec1c94f5706751212de0012deba260f1c532e946bc030e13ed2cf0c81289d89d9da588559b5fb54c45dff026fdba36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
